package main

import (
	"fmt"
	"os"
	"path/filepath"
)

const tmuxConfigContent = `# generated by zed-tmux - do not edit
# this file is overwritten on every zed-tmux startup

set -g status off
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
unbind s
unbind (
unbind )
unbind L
unbind $
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -sg escape-time 10
set -g history-limit 50000
`

func ensureConfig() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("get home dir: %w", err)
	}
	configDir := filepath.Join(home, ".config", "zed-tmux")
	if err := os.MkdirAll(configDir, 0o755); err != nil {
		return "", fmt.Errorf("create config dir: %w", err)
	}
	configPath := filepath.Join(configDir, "tmux.conf")
	if err := os.WriteFile(configPath, []byte(tmuxConfigContent), 0o644); err != nil {
		return "", fmt.Errorf("write config: %w", err)
	}
	return configPath, nil
}
